# Examen Parcial n°1 2da Parte - TLP3 - Python para Ciencia de Datos.

**A partir del datasets brindado, realizar los siguientes procedimientos:**

* Importar datasets con Pandas.
* Explorar los datos con los metodos correspondientes. 
* Limpieza de los datos (Normalización de datos).
* Obtener estadisticas.
* Mostrar los datos procesados con graficos utilizando la libreria Matplotlib.
* Exportar el contenido a un archivo sqlite utilizando PANDAS.


**Importante: Se debe documentar cada procedimiento realizado, siguiendo la siguiente estructura:**

1. Celda de Markdown (Documentación)
2. Código (Sin comentarios, se debe documentar lo sufiente solo en la celda de markdown).


### Criterios de Evaluación:

1. No esta permitido el uso de IAs durante el examen. (Desactivar Copilot o cualquier herramienta de IA para autocompletar codigo.)

2. Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).

3. Comentarios claros y concisos que expliquen el propósito de cada sección del código en una celda de markdown antes del código.

4. Utilizar mensajes de commit descriptivos. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE).

5. Entrega en tiempo y forma (Parciales entregados fuera de hora o con commits pasados el horario de entrega quedará invalidado.)

6. Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: 
**parcial1_tlp3_nombre_apellido**).

7. Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter.

8. Deben trabajar con el datasets adjunto.

9. Una vez finalizado el examen, los resultados deben quedar guardados debajo de cada celda (NO EJECUTAR LA OPCIÓN "borrar todas las salidas").

**Importante:** Una vez finalizado el examen, marcar como completado en el classroom.

## Actividades: 
### 1. Importación del Dataset con Pandas

En esta sección, se debe utilizar la librería Pandas para cargar el archivo CSV que contiene los datos de VOTACIONES en un Datasets.

### 2. Exploración Inicial de los Datos

A continuación, se deben emplear métodos de Pandas para obtener una visión general del dataset. 
- 2.1: Visualizar las primeras filas y ultimas.
- 2.2: Obtener informacion del df con su metodo correspondiente.
- 2.3: Hacer un conteo de valores nulos.

### 3. Limpieza y Normalización de los Datos

- 3.1. Esta etapa crucial deben aplicar la corrección de diversos errores presentes en el dataset. Se abordarán los valores faltantes (Deben aplicar los metodos que ustedes crean convenientes **(Solo 1)**, por ejemplo: Eliminación de filas, cubrir valores con media, mediana, etc.)
- 3.2: La columna Fecha deberan pasarla al tipo datetime con su metodo correspondiente.
- 3.3: Corregir las mayusculas en el caso de Nombre y Apellido (Si es que corresponde.)
- 3.4: En el caso de los votos, aplicar mayusculas a cada fila.
- 3.5 EL campo DNI debe ser del tipo INT.


### 4. Obtención de Estadísticas Descriptivas

Después de la limpieza, deben hacer lo siguiente: 

- 4.1: calcular nuevamente las estadísticas descriptivas para observar el impacto del proceso de limpieza en los datos numéricos.
- 4.2: Calcular estadísticas específicas por grupo (Agrupar dos columnas).

### 5. Visualización de los Datos con Matplotlib

En esta sección, deben utilizar la librería Matplotlib para crear **UNA** visualización que permitan comprender mejor los datos de ventas.El grafico es a elección, puede crear **UNO** de los siguientes: histogramas, diagramas de dispersión, gráficos de barras y graficos de torta.

### 6. Exportación a Archivo SQLite

Finalmente, deben utilizar la funcionalidad de Pandas para guardar el DataFrame procesado en una base de datos SQLite. Deben hacer una conexión y hacer una consulta para ver si los datos fueron cargados correctamente.

1.Se importa la librería pandas y luego se importa el archivo CSV con esta libreria.

In [291]:
import pandas as pd
df = pd.read_csv("votaciones.csv")
df.head(2)

    nombre apellido         dni     provincia  voto fecha_votacion
0  pánfilo    pombo  34787190.0  buenos aires  nulo     2024-11-22
1   albina  heredia  48336819.0      santa fe  nulo     2024-04-24

- 2.1. Se visualizan las primeras 5 columnas con el método HEAD y las últimas 5 con el método TAIL de la libreria Pandas. 
- 2.2. Se obtiene información acerca del DataFrame con el método INFO. 
- 2.3 Se realiza un conteo de los valores nulos de cada columna con el método NUNIQUE.

In [292]:
print("Primeras 5 \n", df.head(5))
print("Últimas 5 \n", df.tail(5))
print( df.info())
print("Datos nulos \n",df.isna().sum())

Primeras 5
     nombre apellido         dni     provincia  voto fecha_votacion
0  pánfilo    pombo  34787190.0  buenos aires  nulo     2024-11-22
1   albina  heredia  48336819.0      santa fe  nulo     2024-04-24
2      NaN   solano  49179364.0       neuquen  nulo     2024-05-20
3   salomé   barrio  43725639.0  buenos aires   NaN     05-06-2024
4   matías  esteban  30599927.0         chaco    no     10-07-2023
Últimas 5
        nombre apellido         dni provincia  voto fecha_votacion
96      carla    vidal  15161718.0  misiones  nulo     2023-09-12
97   federico  barrios  16171819.0   neuquen    no     11-09-2023
98      belen     vera  17181920.0   tucuman    sí     2023-09-10
99    gustavo    gauna  18192021.0  santa fe  nulo     09-09-2023
100     rocio    avila  19202122.0   formosa    no     08-09-2023
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nombre          91 non-null     object
 1   apellido        94 non-null     object
 2   dni             90 non-null     float64
 3   provincia       95 non-null     object
 4   voto            96 non-null     object
 5   fecha_votacion  95 non-null     object
dtypes: float64(1), object(5)
memory usage: 4.9+ KB
None
Datos nulos
 nombre            10
apellido           7
dni               11
provincia          6
voto               5
fecha_votacion     6
dtype: int64

- 3.1: Se quitan todos los valores no-númericos de las tablas porque no suman valor para el recuento de votos.
- 3.3: Se ponen las capitalizan de las 2 columnas (nombre,apellido) con el método CAPITALIZE
- 3.4: Se ponen las mayúsculas de la columna voto con el método UPPER
- 3.5: Se transforma la columna dni a números enteros con la función ASTYPE.

In [ ]:
df["nombre"] = df["nombre"].str.capitalize()
df["apellido"] = df["apellido"].str.capitalize()
df["voto"] = df["voto"].str.upper()

df.dropna(inplace=True)
df.replace("SÍ","SI",inplace=True)
df.drop(labels=(df[(df.voto != "SI") & (df.voto != "NO")].index), inplace=True)
df.dni = df.dni.astype("int32")

           nombre   apellido       dni     provincia voto fecha_votacion
4          Matías    Esteban  30599927         chaco   NO     10-07-2023
6        Gervasio        Bou  33761658       mendoza   NO     23-09-2023
7         Brígida     Angulo  22169546         chaco   NO     2024-05-02
10       Verónica     Posada  35293135      santa fe   NO     2024-09-15
11      Anastasio     Galvez  42313020      santa fe   NO     01-11-2023
14       Baudelio   Sanabria  24036189       tucuman   NO     2024-04-04
17      Juan josé     Suarez  29043980      santa fe   NO     23-10-2024
19         Ramiro      Checa  31711663         chaco   NO     2024-08-25
25        Guiomar   Aramburu  17514893    corrientes   SI     22-11-2024
32          Lucas       Pozo  18472805       neuquen   SI     2024-05-03
36        Roberto  Sevillano  32940620       mendoza   SI     06-08-2024
37         Rufino      Jordá  25186385       cordoba   SI     2023-05-13
39       Gregorio      Jódar  40808148       tucuman   NO     17-12-2024
40         Lupita      Prado  14649451       tucuman   SI     2023-09-27
41   Miguel ángel  Castañeda  48066419      misiones   NO     13-08-2023
44            Luz     Alemán  13652459    corrientes   SI     2024-12-28
46      Victorino       Cabo  23310842       tucuman   SI     2025-03-25
48         Regina     Bayona  29097522       neuquen   NO     2024-06-28
50          Lucas  Rodriguez  12345678  buenos aires   SI     12-10-2023
51          María      Perez  23456789      santa fe   NO     2023-10-14
56         Matias     Molina  67890123         chaco   SI     12-10-2023
57         Carlos    Aguirre  78901234       formosa   NO     11-10-2023
60        Luciana       Rios  12398765      san juan   SI     10-10-2023
61         Julian    Navarro  23419876  buenos aires   NO     2023-10-09
63          Elias  Dominguez  34521987         salta   SI     2023-10-08
65         Martin        Paz  56743219       tucuman   NO     2023-10-07
66      Florencia     Flores  67854320       mendoza   SI     07-10-2023
69         Franco     Ibañez  90187653       cordoba   NO     05-10-2023
72         Emilia      Rojas  23423423  buenos aires   NO     02-10-2023
74        Julieta     Castro  45645645         salta   SI     30-09-2023
75         Camila       Mena  56756756      santa fe   NO     2023-09-29
76        Joaquin       Cano  67867867       tucuman   SI     29-09-2023
78         Daniel    Quiroga  89089089  buenos aires   SI     28-09-2023
80          Pablo     Pineda  11223344       mendoza   NO     2023-09-26
81       Milagros    Gimenez  22334455       formosa   SI     2023-09-25
83         Romina     Acosta  44556677         salta   NO     2023-09-24
85       Lucrecia    Carrizo  55667788       tucuman   NO     23-09-2023
87        Micaela   Ferreyra  77889900       cordoba   SI     21-09-2023
88        Esteban     Prieto  88990011      santa fe   NO     20-09-2023
90          Bruno      Tapia  10111213       neuquen   SI     18-09-2023
91           Alma    Pereyra  11121314       mendoza   NO     17-09-2023
94         Yesica     Ospina  13141516  buenos aires   NO     2023-09-14
95        Leandro     Torres  14151617       cordoba   SI     13-09-2023
97       Federico    Barrios  16171819       neuquen   NO     11-09-2023
98          Belen       Vera  17181920       tucuman   SI     2023-09-10
100         Rocio      Avila  19202122       formosa   NO     08-09-2023

3.2 Intenté hacer un parser de fechas pero me falta agregarle al dataframe.

In [ ]:
separador = df.fecha_votacion.str.split("-")
fechas = []
for fecha in separador:
    if (fecha[0] == "2023"):
        fechas.append(pd.Timestamp(year=int(fecha[0]),month=int(fecha[1]),day=int(fecha[2])))
    if (fecha[2] == "2023"):
        fechas.append(pd.Timestamp(year=int(fecha[2]),month=int(fecha[1]),day=int(fecha[0])))
    if (fecha[0] == "2024"):
        fechas.append(pd.Timestamp(year=int(fecha[0]),month=int(fecha[1]),day=int(fecha[2])))
array = pd.array(fechas)
iterador = 0
indice = (df.fecha_votacion.index)[iterador]

np.int64(4)

- Esto de acá no me salió profe.
- 4.1 : Se visualiza la descripción del DataFrame con la función DESCRIBE.
- 4.2 : Se agrupa los votos y nombres por Provincia

In [ ]:
print(df.describe())
grupo = df.groupby("provincia")[["voto","nombre"]]
print(grupo)

                dni
count  4.600000e+01
mean   3.619293e+07
std    2.352911e+07
min    1.011121e+07
25%    1.775437e+07
50%    2.907075e+07
75%    4.746123e+07
max    9.018765e+07
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000027E94D89220>